[project]
id = "io.buildpacks.nurse"
name = "nurse-Website"
version = "1.0.0"

[build]

[[build.buildpacks]]
id = "me/symfony-env"

  [build.buildpacks.script]
  api = "0.6"
  inline = "env | grep SYMFONY_ | cut -c9- > .env"

[[build.buildpacks]]
uri = "heroku/php"
[[build.buildpacks]]
uri = "heroku/procfile"
